<a href="https://colab.research.google.com/github/medvindeva/DVT/blob/main/Ex2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import pandas as pd
import sqlite3

# Dataset path (not strictly needed for direct file path, but kept for context)
path = "/content"

# Directly use the provided CSV file path
csv_file = "fifa_world_cup_2026_player_performance.csv"

print("CSV file:", csv_file)

# Load dataset
df = pd.read_csv(
    os.path.join(path, csv_file),
    low_memory=False
)

print("\nFirst 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

print("\nDataset Information:")
df.info()

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nStatistical Description:")
display(df.describe().T)

print("\nMissing Values:")
display(df.isnull().sum().sort_values(ascending=False))

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nTeams:")
display(df["team"].value_counts().head(10))

print("\nPositions:")
display(df["position"].value_counts())

print("\nNationalities:")
display(df["nationality"].value_counts().head(10))

print("\nCorrelation:")
display(df.corr(numeric_only=True))

# Export CSV
df.to_csv(
    "fifa_player_performance_cleaned.csv",
    index=False
)

# Export Excel
df.to_excel(
    "fifa_player_performance.xlsx",
    index=False
)

# SQLite Database
conn = sqlite3.connect(
    "fifa_player_performance.db"
)

df.to_sql(
    "player_performance",
    conn,
    if_exists="replace",
    index=False
)

conn.close()

print(
    "\nCSV, Excel and SQLite database files "
    "created successfully."
)

CSV file: fifa_world_cup_2026_player_performance.csv

First 5 rows:

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

Last 5 rows:

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  object
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(43), object(14)
memory usage: 31.2+ MB

Shape:
(54600, 75)

Columns:
['player_id', 'player_name', 'age', 'nationality', 'team', 'jersey_number', 'position', 'height_cm', 'weight_kg', 'preferred_foot', 'club_name', 'market_value_eur', 'match_id', 'match_date', 'stadium', 'city', 'opponent_team', 'tournament_stage', 'match_result', 'goals_team', 'goals_opponent', 'minutes_played', 'goals', 'assists', 'shots', 'shots_on_target', 'expected_goals_xg', 'expected_assists_xa', 'key_passes', 'successful_passes', 'total_passes', 'pass_accuracy', 'dribbles_attempted', 'successful_dribbles', 'crosses', 'successful_crosses', 'tackles', 'interceptions', 'clearances', 'blocks', 'aerial_duels_won', 'aerial_duels_lost', 'recoveries', 'defensive_actions', 'fouls_committed', 'fouls_suffered', 'yellow_cards', 'red_cards', 'offsides', 'saves', 'save_percentage', 'punches', 'clean_sheet', 'goals_conceded', 'penalty_saves', 'distance_covered_km', 'sprint_distance_km', 'top_speed_kmh', 'accelerations', 'decelerations', 'stamina_score', 'player_rating', 'performance_score', 'offensive_contribution', 'defensive_contribution', 'possession_impact', 'pressure_resistance', 'creativity_score', 'consistency_score', 'clutch_performance_score', 'total_goals_tournament', 'total_assists_tournament', 'total_minutes_tournament', 'player_of_match_awards', 'tournament_rating']

Data Types:
player_id                    object
player_name                  object
age                           int64
nationality                  object
team                         object
                             ...
total_goals_tournament        int64
total_assists_tournament      int64
total_minutes_tournament      int64
player_of_match_awards        int64
tournament_rating           float64
Length: 75, dtype: object

Statistical Description:

,count,mean,std,min,25%,50%,75%,max
age,54600.0,2.629648e+01,4.067519e+00,17.0,23.0,26.0,29.0,39.0
jersey_number,54600.0,1.350000e+01,7.500069e+00,1.0,7.0,13.5,20.0,26.0
height_cm,54600.0,1.816543e+02,6.277792e+00,163.0,177.0,182.0,186.0,200.0
weight_kg,54600.0,7.575485e+01,3.951481e+00,65.0,73.0,76.0,78.0,87.0
market_value_eur,54600.0,2.008445e+07,2.718866e+07,528822.0,4444778.0,10271107.0,23420128.0,200000000.0
...,...,...,...,...,...,...,...,...
total_goals_tournament,54600.0,6.439927e-01,1.093781e+00,0.0,0.0,0.0,1.0,10.0
total_assists_tournament,54600.0,6.076007e-01,9.315267e-01,0.0,0.0,0.0,1.0,8.0
total_minutes_tournament,54600.0,2.723003e+02,1.168062e+02,0.0,184.0,268.0,359.0,615.0
player_of_match_awards,54600.0,3.065934e-02,2.065200e-01,0.0,0.0,0.0,0.0,4.0
tournament_rating,54600.0,3.634046e+00,3.163411e+00,0.0,0.0,5.4,6.4,9.5

Missing Values:

player_id                   0
player_name                 0
age                         0
nationality                 0
team                        0
                           ..
total_goals_tournament      0
total_assists_tournament    0
total_minutes_tournament    0
player_of_match_awards      0
tournament_rating           0
Length: 75, dtype: int64

Duplicate Rows:
0

Teams:

team
Qatar           1716
Jamaica         1534
Morocco         1430
Netherlands     1404
Italy           1378
Saudi Arabia    1352
Belgium         1326
Turkey          1300
Croatia         1274
Scotland        1274
Name: count, dtype: int64

Positions:

position
Defender      18900
Midfielder    16800
Forward       12600
Goalkeeper     6300
Name: count, dtype: int64

Nationalities:

nationality
Qatari      1716
Jamaican    1534
Moroccan    1430
Dutch       1404
Italian     1378
Saudi       1352
Belgian     1326
Turkish     1300
Croatian    1274
Scottish    1274
Name: count, dtype: int64

Correlation:

,age,jersey_number,height_cm,weight_kg,market_value_eur,goals_team,goals_opponent,minutes_played,goals,assists,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
age,1.000000,-0.191316,0.124882,0.093327,-0.068914,-6.428752e-03,1.683938e-03,-0.022833,-0.036548,-0.027272,...,-0.052197,-0.055096,-0.147483,-0.057637,-0.006452,-0.099839,-0.098019,-0.011190,-0.025517,-0.038990
jersey_number,-0.191316,1.000000,-0.486071,-0.319660,0.187251,4.453502e-17,4.339367e-17,0.061657,0.182235,0.110867,...,0.074454,0.034995,0.568534,0.034015,0.008626,0.526784,0.364273,0.014613,0.090411,0.110570
height_cm,0.124882,-0.486071,1.000000,0.630950,-0.112356,2.419965e-03,-4.297944e-03,-0.041854,-0.081591,-0.068021,...,-0.072385,-0.013760,-0.314955,-0.018848,-0.001603,-0.244723,-0.224186,-0.010504,-0.047627,-0.079246
weight_kg,0.093327,-0.319660,0.630950,1.000000,-0.073950,-6.431085e-03,1.289886e-03,-0.021524,-0.060550,-0.039387,...,-0.036368,-0.019334,-0.184050,-0.021363,-0.000473,-0.168261,-0.127640,-0.001755,-0.033163,-0.047990
market_value_eur,-0.068914,0.187251,-0.112356,-0.073950,1.000000,-3.511289e-03,1.612354e-03,0.017773,0.093392,0.081924,...,0.347035,0.594907,0.466853,0.624168,0.111797,0.121565,0.088259,0.000860,0.088152,0.074993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
total_goals_tournament,-0.099839,0.526784,-0.244723,-0.168261,0.121565,6.372242e-03,2.695916e-03,0.072074,0.341717,0.078241,...,0.042889,0.026330,0.312111,0.026546,0.008342,1.000000,0.278294,0.241801,0.155998,0.091238
total_assists_tournament,-0.098019,0.364273,-0.224186,-0.127640,0.088259,-3.486700e-03,-2.818644e-03,0.079970,0.077165,0.307885,...,0.115917,0.030114,0.296283,0.024850,0.009065,0.278294,1.000000,0.272720,0.141938,0.097110
total_minutes_tournament,-0.011190,0.014613,-0.010504,-0.001755,0.000860,-2.085579e-03,-3.046484e-03,0.312868,0.064891,0.069086,...,0.209072,-0.000315,0.007218,-0.001877,-0.000082,0.241801,0.272720,1.000000,0.102657,0.260638
player_of_match_awards,-0.025517,0.090411,-0.047627,-0.033163,0.088152,3.695465e-04,-1.793868e-03,0.143611,0.324354,0.327383,...,0.174037,0.072808,0.110730,0.077475,0.024091,0.155998,0.141938,0.102657,1.000000,0.144761
tournament_rating,-0.038990,0.110570,-0.079246,-0.047990,0.074993,8.611773e-03,-7.207199e-03,0.835092,0.216853,0.203989,...,0.618330,0.065343,0.086443,0.070183,0.013002,0.091238,0.097110,0.260638,0.144761,1.000000